package com.weappsinc.watertracker.app.core.constants

object AppText {
    const val SPLASH_TITLE = "Water Tracker"
    const val SPLASH_BACKGROUND_DESC = "Splash background"
    const val SPLASH_ICON_DESC = "Splash icon"
    const val SELECT_GENDER_TITLE = "Select Gender?"
    const val MALE = "Male"
    const val FEMALE = "Female"
    const val OTHER = "Other/Prefect not to diclose"
    const val NEXT = "NEXT"
    const val AGE_TITLE = "How old are you?"
    const val TALL_TITLE = "How tall are you?"
    const val WEIGHT_TITLE = "How much do you weigh?"
    const val EXERCISE_TITLE = "How much exercise do you each week?"
    const val EXERCISE_LOW = "Low Exercise"
    const val EXERCISE_MODERATE = "Moderate Exercise"
    const val EXERCISE_HIGH = "High exercise"

    const val WATER_GOAL_TITLE = "Your daily goal is"
    const val WATER_GOAL_DESC = "This number is calculated based on your height, weight, and daily activity level."
    const val ADJUST = "Adjust"
    const val SAVE = "SAVE"
    const val START = "START"
    const val UNIT_ML = "ml"
    const val UNIT_L = "l"

    const val HOME_TAB_WATER = "Water"
    const val HOME_TAB_BMI = "BMI"
    const val HOME_TAB_ME = "Me"
    const val TAB_TODO_PLACEHOLDER = "TODO"

    const val TRACKER_TITLE = "Water Tracker"
    const val STREAK_SUFFIX = "Day - Streak"
    const val TODAY_PROGRESS_LABEL = "Tiến độ hôm nay"
    const val TODAY_GOAL_DONE_LABEL = "Hoàn thành mục tiêu hôm nay 🎉"
    const val GOAL_CARD_LABEL = "Mục tiêu"
    const val REMINDER_CARD_LABEL = "Nhắc nhở sắp tới"
    /** Giờ nhắc: để trống — chỉ UI, domain nhắc lịch làm sau. */
    const val REMINDER_PLACEHOLDER = ""
    /** Mẫu UI theo design (chưa gắn scheduler). */
    const val REMINDER_UI_SAMPLE_TIME = "09:45 AM"
    const val REPORT_TITLE = "Báo cáo"
    const val REPORT_DETAILS = "Chi tiết"
    const val REPORT_TITLE_SCREEN = "Report"
    const val REPORT_TAB_DAY = "Day"
    const val REPORT_TAB_WEEK = "Week"
    const val REPORT_TAB_MONTH = "Month"
    const val REPORT_SUMMARY_TODAY = "TODAY"
    const val REPORT_SUMMARY_GOAL = "GOAL"
    const val REPORT_SUMMARY_AVG_DAY = "AVG/DAY"
    const val REPORT_SUMMARY_TOTAL = "TOTAL"
    const val REPORT_RECORD_HEADER = "Record"
    const val DRINK = "DRINK"
    const val DRINK_AMOUNT_TITLE = "Amount of water"
    const val GOAL_DONE_DIALOG_TITLE = "Chúc mừng bạn đã hoàn thành\nmục tiêu"
    const val CLOSE = "Đóng"

    val WEEKDAY_LABELS_VN = listOf("T2", "T3", "T4", "T5", "T6", "T7", "CN")
}
